name: "Python Container Action Template"
description: "Get started with Python Container actions"
author: "Isac Arvidsson"
inputs:
  filePath:
    description: "Input to use"
    default: "world"
  passwordSecret:
    description: "password for email"
  usernameSecret:
    description: "username for email"
  domainSecret:
    description: "domain for email"
outputs:
  myOutput:
    description: "Output from the action"
runs:
  using: "docker"
  image: "Dockerfile"
