name: Lint
on:
  push:
  
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Checkout
        uses: actions/checkout@v1
      - name: Get README.md
        run: |
          git fetch
          diffPaths=$(git diff ${{ github.event.pull_request.head.sha }} ${{ github.event.pull_request.base.sha }} --name-only)
          echo "::set-output name=paths=::hejhej"
        id: get-diff
      - name: run python
        #run: python3 main.py
        uses: ./
        with:
          filePath: ${{ steps.get-diff.outputs.paths}}
