name: Notifier
on:
  push:
  
jobs:
  Notifier:
    name: Notifier
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Checkout
        uses: actions/checkout@v1
      - name: Get README.md
        run: | 
          git fetch --quiet 
          echo "::set-output name=paths=::$(git diff ${{ github.event.pull_request.head.sha }} ${{ github.event.pull_request.base.sha }} --name-only)"
        id: get-diff
      - name: run python
        #run: python3 main.py
        uses: ./
        with:
          filePath: ${{steps.get-diff.outputs.paths}}
